### ISSUE TITLE
When will the model be ready to the public?

### ISSUE THREAD

**Issue by DabiaoMa** [sotelo/parrot#8]
Hi, 

This project is really promising and I am eagerly waiting for the completion of it. While what do you mean by saying ' the current version is not ready for replication'?  Does it mean some codes are missing or the structure of the code is kind of messy?

Best,

**Comment by begeekmyfriend** [comment]
What did your mean on `the current version is not ready for replication`?

**Comment by sotelo** [comment]
The code is very messy as it was my research repo and it's also missing some stuff. We're working on a new version for it. However, we have a lot of work to do besides it, so we don't have a release date in mind at the moment.
